name: qawolf

on:
  push:
    paths:
      - ".github/workflows/qawolf.yml"
      - "src/**"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1

      - uses: microsoft/playwright-github-action@v1

      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('app/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install
        working-directory: ./src

      - name: Run app
        run: npm run dev
        working-directory: ./src

      - name: Test app
        env:
          APP_URL: http://localhost:3000
          ACCOUNT_SID: AC38b3c9b5fa7a924bfaf3f0811fd4e5bb
          API_KEY: SKf4e40776608469c77f34c5dea0b84480
          API_SECRET: yVbLFZCysfxTxzBGlz8u0pkNNFMdHoy
        run: npm run test
        working-directory: ./src
